version: '3.8'

services:
  app:
    build: .
    container_name: cep-temp-api
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - PORT=8080
    env_file:
      - .env
